# Docker Compose служит для сборки нескольких контейнеров
# С помощью данного инструмента можно создать контейнер с приложением и БД, после чего запускать их вместе
version: '3'
services:
  app:                            # Собираем сервис приложения
    container_name: hr-app
    build: .
    ports:
      - 8080:8080                 # Явно указываем задействованные порты
    restart: on-failure           # При ошибке выполняем перезапуск
    depends_on:
      - hr-postgres        # Указываем, что контейнер с приложением должен запуститься только после БД
    networks:
      - hrdep                 # Явно привязываем контейнер к внутреннему мосту между двумя сервисами


  hr-postgres:             # Собираем сервис БД
    image: postgres:latest
    container_name: hr_postgres
    environment:                  # Указываем переменные окружения (пока явно, лучше шифровать)
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=feklistova
    ports:                        # Пробрасываем порты из контейнера
      - '5432:5432'
    networks:                     # Привязываемся к той же сети
      - hrdep

networks:                         # Настраиваем сетевой мост, используемый для связи контейнеров
  hrdep:
    driver: bridge